[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | __pycache__
)/
'''

[tool.ruff]
line-length = 100
target-version = "py310"
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C90", # mccabe complexity
]
ignore = [
    "E203",  # whitespace before ':' (conflicts with black)
    "E266",  # too many leading '#' for block comment
    "E501",  # line too long (handled by black)
]
fix = true
exclude = [
    "build",
    "dist",
    ".venv",
    "__pycache__",
    "*.egg-info",
]

[tool.mypy]
python_version = "3.10"
strict = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
exclude = [
    "tests/",
    ".venv/",
    "build/",
]

[[tool.mypy.overrides]]
module = [
    "scipy.*",
    "pandas.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-ra -q --cov=greyoak_score --cov-report=term-missing:skip-covered --cov-report=html --cov-fail-under=80"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.coverage.run]
source = ["greyoak_score"]
omit = [
    "*/tests/*",
    "*/__pycache__/*",
    "*/site-packages/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "@abstract",
]
