# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# GreyOak Score Engine - Main Configuration
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Version: 1.0.0
# Last Updated: 2024-10-08
# 
# CRITICAL: All parameters here are used by the scoring engine.
# NO hard-coded values in code - everything must be configured here.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

version: "1.0.0"

# Mode: "production" or "test"
# NEVER use "test" in production - looser thresholds for debugging only
mode: production

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Pillar Weights (Section 4.3: Sector-Specific Mode Weights)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Each sector/mode combination has weights for F, T, R, O, Q, S
# MUST sum to 1.0 (validated at load time)

pillar_weights:
  trader:  # Short-term mode (≈20 trading days)
    default:
      F: 0.12
      T: 0.32
      R: 0.16
      O: 0.08
      Q: 0.04
      S: 0.28
    
    metals:  # High volatility, momentum-driven
      F: 0.08
      T: 0.38
      R: 0.14
      O: 0.08
      Q: 0.02
      S: 0.30
    
    banks:  # Fundamentals + flows matter even in short-term
      F: 0.35
      T: 0.08
      R: 0.06
      O: 0.20
      Q: 0.08
      S: 0.23
    
    psu_banks:  # Similar to banks
      F: 0.35
      T: 0.08
      R: 0.06
      O: 0.20
      Q: 0.08
      S: 0.23
    
    fmcg:  # Defensive, less momentum
      F: 0.30
      T: 0.10
      R: 0.08
      O: 0.15
      Q: 0.12
      S: 0.25
    
    it:  # Balanced
      F: 0.15
      T: 0.28
      R: 0.14
      O: 0.10
      Q: 0.08
      S: 0.25
    
    auto_caps:  # Mid-cycle, balanced
      F: 0.15
      T: 0.30
      R: 0.15
      O: 0.10
      Q: 0.05
      S: 0.25
    
    diversified:  # Balanced
      F: 0.12
      T: 0.32
      R: 0.16
      O: 0.08
      Q: 0.04
      S: 0.28
  
  investor:  # Long-term mode (≈120 trading days)
    default:
      F: 0.38
      T: 0.10
      R: 0.08
      O: 0.18
      Q: 0.12
      S: 0.14
    
    metals:  # Still cyclical, sector momentum matters
      F: 0.25
      T: 0.15
      R: 0.10
      O: 0.10
      Q: 0.10
      S: 0.30
    
    banks:  # Fundamentals + quality dominant
      F: 0.45
      T: 0.05
      R: 0.05
      O: 0.25
      Q: 0.12
      S: 0.08
    
    psu_banks:  # Similar to banks
      F: 0.45
      T: 0.05
      R: 0.05
      O: 0.25
      Q: 0.12
      S: 0.08
    
    fmcg:  # Quality + fundamentals
      F: 0.45
      T: 0.05
      R: 0.05
      O: 0.20
      Q: 0.15
      S: 0.10
    
    it:  # Quality matters long-term
      F: 0.40
      T: 0.08
      R: 0.07
      O: 0.18
      Q: 0.15
      S: 0.12
    
    auto_caps:  # Balanced
      F: 0.38
      T: 0.10
      R: 0.08
      O: 0.18
      Q: 0.12
      S: 0.14
    
    diversified:  # Balanced
      F: 0.38
      T: 0.10
      R: 0.08
      O: 0.18
      Q: 0.12
      S: 0.14

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Sub-Pillar Weights (Section 5: Pillar Definitions)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Fundamentals Pillar (Section 5.1)
fundamentals:
  non_financial:  # For non-banking stocks
    roe_3y: 0.35
    sales_cagr_3y: 0.25
    eps_cagr_3y: 0.20
    valuation: 0.20  # PE or EV/EBITDA (lower better)
  
  banking:  # For banks/NBFCs - EXCLUSIVE, no mixing
    roa_3y: 0.30
    roe_3y: 0.25
    gnpa_pct: 0.20  # Lower better
    pcr_pct: 0.15   # Higher better
    nim_3y: 0.10

# Technicals Pillar (Section 5.2)
technicals:
  weights:
    above_200: 0.20
    golden_cross: 0.15
    rsi: 0.20
    breakout: 0.25
    volume: 0.20
  
  rsi_bands:
    oversold: 30
    overbought: 70
  
  breakout:
    atr_multiplier: 0.75  # gap / (0.75 * ATR)
    close_pct: 0.01       # or 1% of close, whichever is larger

# Relative Strength Pillar (Section 5.3)
relative_strength:
  horizon_weights:
    "1M": 0.45  # 21 days
    "3M": 0.35  # 63 days
    "6M": 0.20  # 126 days
  
  alpha_weights:
    sector: 0.6  # Weight for stock vs sector excess return
    market: 0.4  # Weight for stock vs NIFTY excess return

# Ownership Pillar (Section 5.4)
ownership:
  weights:
    promoter_hold: 0.30
    pledge: 0.30
    fii_dii_change: 0.40
  
  # Pledge penalty curve (Section 5.4)
  # Penalties are SUBTRACTED from normalized pledge points
  pledge_penalty_curve:
    - fraction: 0.00
      penalty: 0
    - fraction: 0.05
      penalty: 5
    - fraction: 0.10
      penalty: 10
    - fraction: 0.20
      penalty: 20
    - fraction: 1.00
      penalty: 30

# Quality Pillar (Section 5.5)
quality:
  weights:
    roce_3y: 0.65
    opm_stability: 0.35  # OPM stdev over 12Q (lower better)

# Sector Momentum Pillar (Section 5.6)
sector_momentum:
  horizon_weights:
    "1M": 0.20
    "3M": 0.30
    "6M": 0.50

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Risk Penalty (Section 7.1)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

risk_penalty:
  # Sector-specific RP caps
  caps:
    default: 20
    metals: 18
    psu_banks: 18
    fmcg: 12
    it: 12
    pharma: 12
  
  # Liquidity penalties (MTV in ₹Crores)
  liquidity:
    trader:
      - threshold: 5.0   # ≥₹5Cr
        penalty: 0
      - threshold: 3.0   # ₹3-5Cr
        penalty: 5
      - threshold: 0.0   # <₹3Cr
        penalty: 10
    
    investor:
      - threshold: 5.0   # ≥₹5Cr
        penalty: 0
      - threshold: 2.0   # ₹2-5Cr
        penalty: 5
      - threshold: 0.0   # <₹2Cr
        penalty: 10
  
  # Pledge bins (separate from O pillar penalty and PledgeCap guardrail)
  pledge_bins:
    - threshold: 0.25  # >25%
      penalty: 10
    - threshold: 0.10  # >10%
      penalty: 5
  
  # Volatility penalty
  volatility:
    multiplier: 2.5  # stock.sigma20 > 2.5 × sector.sigma20
    penalty: 5
  
  # Event window penalty
  event_window:
    days: 2  # ±2 days from earnings/board meeting
    penalty: 2
  
  # Governance penalties
  governance:
    auditor_qualification: 2
    board_resignation: 1

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Guardrails (Section 7.5)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

guardrails:
  thresholds:
    production:
      confidence: 0.70        # LowDataHold if confidence < 0.70
      sector_bear_sz: -1.5    # SectorBear if S_z ≤ -1.5
      high_risk_rp: 15        # HighRiskCap if RP ≥ 15
      pledge_cap: 0.10        # PledgeCap if pledge_fraction > 0.10
      low_coverage: 0.25      # LowCoverage if imputed_frac ≥ 0.25
    
    test:  # Looser thresholds for debugging
      confidence: 0.60
      sector_bear_sz: -2.0
      high_risk_rp: 15
      pledge_cap: 0.10
      low_coverage: 0.25

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Banding Thresholds (Section 6: Composite Scoring and Modes)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

banding:
  production:
    strong_buy: 75  # score ≥ 75
    buy: 65         # 65 ≤ score < 75
    hold: 50        # 50 ≤ score < 65
    # avoid: score < 50 (implicit)
  
  test:  # Looser cutoffs for testing
    strong_buy: 70
    buy: 60
    hold: 45
